[package]
name = "vrc-yt-proxy"
version = "1.0.0"
authors = ["Shayne Hartford <shaybox@shaybox.com>"]
edition = "2021"
description = "Play YouTube videos on Quest in VRChat"
readme = "README.md"
repository = "https://github.com/ShayBox/VRC-YT-Proxy"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = { version = "4.3.1", features = ["rustls"] }
regex = "1.7.1"
tokio = "1.26.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
youtube_dl = { version = "0.8.0", default-features = false, features = ["downloader"] }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
