[tasks.build]
command = "cross"
args = [
    "build",
    "--release",
    "--target",
    "aarch64-unknown-linux-gnu",
]

[tasks.copy]
command = "scp"
args = [
    "index.html",
    "ubuntu@vps.shaybox.com:~/vrc-yt-proxy/index.html",
]

[tasks.release]
dependencies = ["build"]
command = "scp"
args = [
    "target/aarch64-unknown-linux-gnu/release/vrc-yt-proxy",
    "ubuntu@vps.shaybox.com:~/vrc-yt-proxy/vrc-yt-proxy",
]
