[package]
name = "manager"
description.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.7", features = ["derive"] }
clap-verbosity-flag = { git = "https://github.com/Shays-Forks/clap-verbosity-flag.git", version = "2.1.1", features = ["tracing"] }
common = { workspace = true, features = ["rustls-tls", "database"] }
dotenvy_macro = { version = "0.15.7", optional = true }
indicatif = "0.17.3"
thirtyfour = "0.32.0-rc.7"
tokio = { version = "1.28.1", features = ["full"] }
tracing-subscriber = "0.3.17"

[features]
default = ["read-write"]
read-write = ["dep:dotenvy_macro"]
