[package]
name = "manager"
description = "Manage the database for my Quest YouTube world"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.8", features = ["derive"] }
common = { workspace = true, features = ["database"] }
dotenvy_macro = "0.15.1"
tokio = { version = "1.26.0", features = ["full"] }
