[package]
name = "common"
description = "Common library"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.39"
youtube_dl = { git = "https://github.com/Shays-Forks/youtube-dl-rs.git", default-features = false, features = ["downloader"] }

[features]
default = ["rustls-tls"]
native-tls = ["youtube_dl/native-tls"]
rustls-tls = ["youtube_dl/rustls-tls"]
