[package]
name = "proxy"
description = "Proxy YouTube videos for Quest"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4.3.1"
regex = "1.7.1"
tokio = "1.26.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
youtube_dl = { git = "https://github.com/Shays-Forks/youtube-dl-rs.git", default-features = false, features = ["downloader"] }

[features]
default = ["rustls-tls"]
native-tls = ["youtube_dl/native-tls", "actix-web/openssl"]
rustls-tls = ["youtube_dl/rustls-tls", "actix-web/rustls"]
