[tasks.release]
command = "cross"
args = ["build", "--release", "--target", "aarch64-unknown-linux-gnu", "--features", "database"]

[tasks.upload]
command = "scp"
args = [
    "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/aarch64-unknown-linux-gnu/release/${CARGO_MAKE_CRATE_NAME}",
    "ubuntu@vps.shaybox.com:~/vrc-yt/${CARGO_MAKE_CRATE_NAME}",
]
