on:
  release:
    types: [ created ]

jobs:
  release:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux-aarch64
            target: aarch64-unknown-linux-gnu
            runner: ubuntu-latest

          - name: Linux-x86_64
            target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Update Rust Toolchain
        run: rustup update stable

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Build Release Binary
        run: |
          cargo install cross
          cross build --release --target ${{ matrix.target }} --package proxy

      - name: Create Zip Archive
        run: zip -j ${{ matrix.name }}.zip target/${{ matrix.target }}/release/proxy

      - name: Upload Zip Archive
        run: gh release upload ${{ github.ref_name }} ${{ matrix.name }}.zip --clobber
